name: Deploy Backend to AWS EC2

# NOTE: Frontend is deployed automatically by AWS Amplify on push to main
# This workflow only handles backend deployment to EC2

on:
  push:
    branches:
      - main
    paths:
      # Only trigger when backend or common packages change
      - 'packages/backend/**'
      - 'packages/common/**'
      - '.github/workflows/**'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build common package
        run: npm run build:common

      - name: Build backend
        run: npm run build:backend

      - name: Run backend tests
        run: npm run test:backend

  deploy-backend:
    name: Deploy Backend to EC2
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Navigate to application directory
            cd /home/${{ secrets.EC2_USERNAME }}/easylegal

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Build common package (required by backend)
            npm run build:common

            # Build backend
            npm run build:backend

            # Run backend tests
            npm run test:backend

            # Remove old database to ensure fresh user data (optional - only if you want to reset)
            # rm -f packages/backend/data/easylegal.db

            # Restart backend with PM2
            # The database will be automatically initialized with authorized users on restart
            pm2 restart easylegal-backend || pm2 start packages/backend/dist/index.js --name easylegal-backend

            # Save PM2 configuration
            pm2 save

            # Show status
            pm2 status
